"""Generate sampler Deployment manifests from a camera registry.

The generated Deployments intentionally default to replicas=0. Turning samplers
on resumes Gemini API calls, so live demo scale-up should stay an explicit
operator action rather than a side effect of re-applying manifests.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "k8s" / "cameras.json"
DEFAULT_OUTPUT = ROOT / "k8s" / "sampler-deployment.yaml"
DEFAULT_IMAGE = "k3d-registry.localhost:5000/vision-sampler:dev"
DEFAULT_NAMESPACE = "surveillance"
DEFAULT_REPLICAS = 0
_DNS_LABEL_RE = re.compile(r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$")


@dataclass(frozen=True)
class Camera:
    camera_id: str
    zone: str
    clip_file: str
    display_name: str = ""

    @property
    def deployment_name(self) -> str:
        return f"sampler-{self.camera_id}"

    @property
    def clip_path(self) -> str:
        return f"/app/data/clips/{self.clip_file}"


def load_cameras(path: Path = DEFAULT_REGISTRY) -> list[Camera]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    records = raw.get("cameras")
    if not isinstance(records, list) or not records:
        raise ValueError(f"{path} must contain a non-empty 'cameras' list")

    cameras: list[Camera] = []
    seen_ids: set[str] = set()
    for index, record in enumerate(records, start=1):
        if not isinstance(record, dict):
            raise ValueError(f"camera #{index} must be an object")
        try:
            camera = Camera(
                camera_id=str(record["camera_id"]).strip(),
                zone=str(record["zone"]).strip(),
                clip_file=str(record["clip_file"]).strip(),
                display_name=str(record.get("display_name", "")).strip(),
            )
        except KeyError as exc:
            raise ValueError(f"camera #{index} missing required field {exc.args[0]!r}") from exc

        _validate_camera(camera, seen_ids)
        seen_ids.add(camera.camera_id)
        cameras.append(camera)
    return cameras


def _validate_camera(camera: Camera, seen_ids: set[str]) -> None:
    if not _DNS_LABEL_RE.fullmatch(camera.camera_id):
        raise ValueError(f"camera_id must be a Kubernetes DNS label: {camera.camera_id!r}")
    if camera.camera_id in seen_ids:
        raise ValueError(f"duplicate camera_id: {camera.camera_id}")
    if not camera.zone or not _DNS_LABEL_RE.fullmatch(camera.zone):
        raise ValueError(f"zone must be a Kubernetes DNS label: {camera.zone!r}")
    if "/" in camera.clip_file or "\\" in camera.clip_file or not camera.clip_file:
        raise ValueError(f"clip_file must be a file name, not a path: {camera.clip_file!r}")


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_manifest(
    cameras: list[Camera],
    *,
    namespace: str = DEFAULT_NAMESPACE,
    image: str = DEFAULT_IMAGE,
    replicas: int = DEFAULT_REPLICAS,
) -> str:
    if replicas != 0:
        raise ValueError("sampler Deployments must default to replicas=0")

    docs = [
        "\n".join(
            [
                "# Generated by scripts/generate_sampler_manifests.py. Do not edit by hand.",
                "# Samplers intentionally default to replicas: 0 to prevent accidental API spend.",
            ]
        )
    ]
    for camera in cameras:
        docs.append(
            f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {camera.deployment_name}
  namespace: {namespace}
  labels:
    app: sampler
    camera: {camera.camera_id}
    zone: {camera.zone}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: sampler
      camera: {camera.camera_id}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9102"
      labels:
        app: sampler
        camera: {camera.camera_id}
        zone: {camera.zone}
    spec:
      containers:
        - name: sampler
          image: {image}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: vision-agent-config
          env:
            - name: CAMERA_ID
              value: {_quote(camera.camera_id)}
            - name: CAMERA_DISPLAY_NAME
              value: {_quote(camera.display_name or camera.camera_id)}
            - name: ZONE
              value: {_quote(camera.zone)}
            - name: CLIP_PATH
              value: {_quote(camera.clip_path)}
          ports:
            - name: metrics
              containerPort: 9102
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi"""
        )
    return "\n---\n".join(docs) + "\n"


def deployment_names(cameras: list[Camera]) -> list[str]:
    return [camera.deployment_name for camera in cameras]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--image", default=DEFAULT_IMAGE)
    parser.add_argument("--namespace", default=DEFAULT_NAMESPACE)
    parser.add_argument("--list-deployments", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    cameras = load_cameras(args.registry)
    if args.list_deployments:
        print("\n".join(deployment_names(cameras)))
        return

    manifest = render_manifest(cameras, namespace=args.namespace, image=args.image)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(manifest, encoding="utf-8")
    print(f"Wrote {len(cameras)} sampler Deployments to {args.output}")


if __name__ == "__main__":
    main()
